### ISSUE TITLE
Unicode Decode Error

### ISSUE THREAD

**Issue by JoePagano** [deanmalmgren/textract#102]
I'm getting an error when attempting to run setup.py on Win8:

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1671: character maps to <undefined>

Would specifying the correct encoding prevent the issue?

**Comment by deanmalmgren** [comment]
Hmmmm... You're getting that error on running `setup.py install`? That's interesting. Can you share the entire traceback for your error?

**Comment by redleader36** [comment]
I was getting this error too.  It is an ebooklib problem.  Install ebooklib from it's Git repo instead of through pip.  More info here: https://github.com/aerkalov/ebooklib/issues/104

**Comment by sbadia** [comment]
Same error on Linux, using python3.5, I just sent a ping on aerkalov/ebooklib#104

**Comment by deanmalmgren** [comment]
Since this is an ebooklib problem, I'm going to close this issue out. I would gladly welcome Windows installation suggestions and there are some ideas for getting started with that in #111. Python3 support is hopefully going to be coming by the end of the day today via #126 + #104 + #116. More soon...
