### ISSUE TITLE
Only working for docx file in Windows

### ISSUE THREAD

**Issue by bamne123** [deanmalmgren/textract#155]
File "C:\ProgramData\Anaconda3\lib\site-packages\textract\parsers\__init__.py", line 58, in process
    return parser.process(filename, encoding, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\textract\parsers\utils.py", line 46, in process
    byte_string = self.extract(filename, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\textract\parsers\pdf_parser.py", line 20, in extract
    return self.extract_pdftotext(filename, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\textract\parsers\pdf_parser.py", line 43, in extract_pdftotext
    stdout, _ = self.run(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\textract\parsers\utils.py", line 84, in run
    stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by afcruzs** [comment]
I am facing this exact same problem, any idea for this?

**Comment by bamne123** [comment]
I have gave solution for pdf file in other issue ticket. For Doc and Docx you have to set path in environment variable of Program files x86. If lib uses some dependent exe. It should solve the issue.

**Comment by afcruzs** [comment]
I think I found out what happens: As textract uses antiword as a backend to convert doc files to docx, antiword must be installed first. From [here](http://www.winfield.demon.nl/) antiword can be downloaded, and you mention, its path must be set. 

I am using Windows-64 bit, but the .exe seems very old and do not work in 64 bits.

**Comment by bamne123** [comment]
Post solution if it works, it didn't worked for me. And i moved to mac as everything works seamlessly.

**Comment by deanmalmgren** [comment]
I'm sorry to hear you're having trouble with textract. :(

If you are able to get textract to work in a windows environment, I'd encourage a contribution to document how to get it set up (see #111).

My hunch here is that you haven't installed all of the [executable dependencies](http://textract.readthedocs.io/en/stable/installation.html), like antiword, tesseract, etc.

The fact that it works for `D:/oldfile.docx` and not `D:/oldfile.doc` sounds unrelated to me. The [doc parser](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/doc_parser.py) uses antiword to directly convert a doc to text—there is no docx intermediary as far as I know. 

Do you have a similar problem as what is reported in #156 or is that different? It would be great to get the windows user experience buttoned up to make textract as easy to use on any platform as possible.

**Comment by afcruzs** [comment]
Hi, yes, the problem is caused by a missing antiword executable. The problem is that the compiled antiword version for windows are very old (16-bit protected mode and 32-bit protected mode), those are from 2005 and has not been updated since. So is not possible to run antiword (hence manipulate .doc files with textract) unless antiword is recompiled for newer windows versions...

I finally moved on to linux and everything runs great. My advice is that if you really want to run textract on windows 10, the linux subsystem is a great alternative, I have tested installing textract inside the linux subsystem and works great. I had to install antiword manually Pillow by following [this](https://askubuntu.com/questions/547656/install-pillow-on-ubuntu-14-04) and to install antiword by typing this: `apt-get install antiword`.

Cons: As you are essentially running linux inside windows, you can access windows files (documents in our case), but you have to configure the python environment from scratch. Furthermore, I have experienced some slow disk-operations, but I guess it may change in the future.

[More info on linux subsystem inside windows](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide)

I do not know if this workaround is enough to make PR to the docs. Let me know :)

**Comment by deanmalmgren** [comment]
Personally, I think it would be amazing to have a contribution for Windows 10 in whatever way makes the most sense. I use virtual environments all the time from my macbook, so I think it makes sense to use a "linux subsystem" from Windows 10. If you're up for it, please add those instructions [here](https://github.com/deanmalmgren/textract/blob/master/docs/installation.rst).

FWIW, the [Ubuntu/Debian installation instructions](http://textract.readthedocs.io/en/stable/installation.html#ubuntu-debian) include several other packages that you should `apt-get install` to have textract work properly. You probably only needed to do `antiword` and `pillow` steps because of your word document focus...

**Comment by deanmalmgren** [comment]
I'm doing a little issue cleaning this morning. If you have a chance to share some Windows 10 documentation, I'd love the PR!
