### ISSUE TITLE
relax the pypi dependency requirements

### ISSUE THREAD

**Issue by krzysztof** [deanmalmgren/textract#170]
First of all, thanks for a great package, it's really cool!

I'm trying to use textract as part of a larger project, however, when I install it from PyPI it imposes rather strict requirements on package versions (and reinstalls them) - are those exact pinning necessary to make it work or is this a shortcut from the past to achieve a stable behavior?

**Comment by deanmalmgren** [comment]
That's a great question @krzysztof. I started pinning versions in 1.5.0 to address issues like #107 that originated from `chardet` version issues. I've been using @pyup-bot to help manage it, but I can appreciate the difficulty in textract requiring specific versions that might conflict with other package dependencies. The main goal is to make sure people don't install `textract` and then run into problems with the functionality "not working" when it's really an issue with a dependency.

I'd be open to relaxing them to being `>=` particular versions or even excluding particular versions. I'm not sure how that works with @pyup-bot but I'm sure we can work something out. What are you thinking here? Do you want to throw a PR together?

**Comment by krzysztof** [comment]
@deanmalmgren I guess the functionality stability is best achieved with unit tests, but since this is quite an aggregation of many different extractors, I am not sure how cumbersome it would be to maintain it.

> I'd be open to relaxing them to being >= particular versions or even excluding particular versions. I'm not sure how that works with @pyup-bot but I'm sure we can work something out. What are you thinking here? Do you want to throw a PR together?

I'll try to find time this week to integrate it with our project and see what constraints I can find.

**Comment by MalikRumi** [comment]
Well, my two cents on this issue is that when installing from pip just now, I ran into this error:
```
...
Running setup.py install for pocketsphinx ... error
...
deps/sphinxbase/src/libsphinxad/ad_pulse.c:44:30: fatal error: pulse/pulseaudio.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```
I did a quick search, and I have a ton of pulseaudio files, but none named pulseaudio.h. But I don't foresee doing a ton of audio extraction, so why does my install have to fail over a peripheral dependency? Can't you make some of these optional, or do a try/except so a failure of dependencies that don't matter to the user don't prevent successful install?
Now, as it happens, this particular issue is probably not your fault, see https://stackoverflow.com/questions/39185141/pocketsphinx-install-fail-raspberry-pi-zero-raspbian-jessie and https://github.com/dpayne/cli-visualizer/issues/15, but I think the point - optional dependencies in a try/except, or select options, or whatever - is still valid.

**Comment by jpweytjens** [comment]
Most of the [advice](https://nvie.com/posts/pin-your-packages/) I've read, suggest pinning the dependencies in order to make an install independent of the currently installed packages. Are there any dependencies in particular which are too strict for your purpose?

@MalikRumi you can install textraxt `1.6.2` with `pip install git+https://github.com/deanmalmgren/textract.git`. This version makes `pocketsphinx` an optional dependency.
